const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sandbox={window:{}};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('static/movement.js','utf8'),sandbox);
const {create,move,walkable}=sandbox.window.GauntletMovement;
const room={code:'A',stage:1,phase:'combat',you:'p',players:[{id:'p',status:'alive'}],movement:{x:100,y:200,speed:145,age:0,slideVx:0,slideVy:0}};
const motion=create();motion.remember({x:0,y:0},1000);motion.update(room,1000);
motion.remember({x:1,y:0},1000);
assert.ok(motion.position(room,1016).x>102,'Respond on the next frame before any server snapshot arrives');
motion.remember({x:0,y:0},1016);
assert.equal(motion.position(room,1048).x,motion.position(room,1016).x,'Key release stops local movement immediately');
motion.remember({x:1,y:1},1048);
const a=motion.position(room,1048),b=motion.position(room,1098);
assert.ok(Math.abs(Math.hypot(b.x-a.x,b.y-a.y)-145*.05)<.001,'Diagonal speed is normalized');
assert.deepEqual(motion.position(room,1700),motion.position(room,1250),'Lost connection caps prediction rather than drifting forever');
room.movement={...room.movement,x:800,y:300};motion.update(room,1710);
assert.ok(motion.position(room,1710).x>=800,'Dash or teleport snaps large corrections');
room.players[0].status='downed';motion.update(room,1720);
assert.equal(motion.position(room,1740).x,800,'Downed heroes cannot predict movement');
const p={x:100,y:200,slideVx:0,slideVy:0};
room.environment={obstacles:[{hp:24,x:200,y:200,radius:24}],zones:[]};
move(room,p,1,0,300,.5);assert.ok(p.x<=164 && p.x>=156,'Swept movement stops before the cover collision boundary');
const blocked=p.x;room.environment.obstacles[0].hp=0;move(room,p,1,0,300,.5);assert.ok(Math.abs(p.x-blocked-150)<.001,'Destroyed cover opens the path');
room.environment.zones=[{kind:'ice',x:p.x,y:200,radius:90}];
move(room,p,1,0,145,.05);const ice=p.x;move(room,p,0,0,145,.05);assert.ok(p.x>ice,'Ice retains intentional momentum');
const town={phase:'town',townHouses:[{x:480,y:250}]};
assert.equal(walkable(town,480,240),false);assert.equal(walkable(town,550,240),true);
town.townInterior='inn';town.innFloor=2;town.innRooms=[{x:320,locked:false},{x:640,locked:true}];
assert.equal(walkable(town,320,200),true);assert.equal(walkable(town,640,200),false);assert.equal(walkable(town,480,380),true);
assert.equal(walkable({phase:'routes'},480,440),true);assert.equal(walkable({phase:'routes'},400,440),false);
console.log('Immediate movement, release, normalized diagonals, stale prediction, teleports, downing, cover, ice, town and fork collisions: OK');
